# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Build and push the project release images.
---
name: Release project images
on:
  release:
    types: [created]

jobs:

  peerpod-ctrl:
    uses: ./.github/workflows/peerpod-ctrl_image.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit
